apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rh1x83rgk-go
  janus-idp.io/tekton: rh1x83rgk-go
  backstage.io/kubernetes-id: rh1x83rgk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rh1x83rgk-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
