apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rh1x83rgk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh1x83rgk-go 
  name: rh1x83rgk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rh1x83rgk-go 
